In [1]:
import numpy as np

In [2]:
# creates 5 random gaussian variables

a = np.random.randn(5)

In [3]:
a

array([ 0.66169276, -1.01333605,  0.36938969, -0.5448767 ,  1.49548877])

In [4]:
a.shape

(5,)

In [5]:
np.dot(a, a.T)

4.1345132868874268

Problem is it is neither a row or column vector, it is a rank 1 array. Hence, good practice in neural network is to specify the ** shape **

In [6]:
a = np.random.randn(5, 1)
a

array([[-0.14008171],
       [-0.35828123],
       [ 0.02925084],
       [ 1.86973004],
       [-0.62280533]])

In [7]:
a.T

array([[-0.14008171, -0.35828123,  0.02925084,  1.86973004, -0.62280533]])

In [10]:
# now can use broadcasting
np.dot(a, a.T)

array([[  1.96228852e-02,   5.01886474e-02,  -4.09750753e-03,
         -2.61914979e-01,   8.72436344e-02],
       [  5.01886474e-02,   1.28365442e-01,  -1.04800267e-02,
         -6.69889182e-01,   2.23139460e-01],
       [ -4.09750753e-03,  -1.04800267e-02,   8.55611586e-04,
          5.46911724e-02,  -1.82175783e-02],
       [ -2.61914979e-01,  -6.69889182e-01,   5.46911724e-02,
          3.49589041e+00,  -1.16447782e+00],
       [  8.72436344e-02,   2.23139460e-01,  -1.82175783e-02,
         -1.16447782e+00,   3.87886473e-01]])

In [14]:
assert(a.shape == (5,1))

In [16]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)

In [18]:
c.shape

(12288, 45)